baseURL = 'https://saxthomasook.github.io/welcome-to-git/'
languageCode = 'nl-nl'
title = 'Technisch Beheer & Monitoring'

# Disable unnecessary features for simple static site
disableKinds = ['taxonomy', 'term', 'RSS', 'sitemap']

[params]
  description = "Information about ITIL, DevOps, CI/CD and Monitoring"
